### PR TITLE
fix: avoid duplicate entries when overriding the manifest

### PR DESCRIPTION
**Pull request by petermuessig**

### CODE REVIEW

**Comment by petermuessig** [comment]
@marianfoo - you need to omit from the build result with the real resource being in the dependencies of the project not with just the string path ;-)

**Comment by petermuessig** [comment]
FYI - I'll also fix the zipper task to show warnings for duplicate resources and skip them

**Comment by petermuessig** [comment]
https://github.com/ui5-community/ui5-ecosystem-showcase/pull/1036

**Comment by marianfoo** [comment]
thanks!

**Pull request merged**
